#!/usr/bin/env bash
# Bash script that pings an IP address

# verifie si un argument a ete donner
if [[ $# -eq 0 ]]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 0
fi

# recuper l'adresse
IP_ADDRESS="$1"

# 5 pings vers l'adresse IP
ping -c 5 "$IP_ADDRESS"
